x = "hello" #string
x = 20 #int
x = 1j #complex
x = ["hello", "hi", "bye"] #list
x = ("tuple", "is", "this") #tuple
x = range(6) # range
x = {"name": "John", "age": 24} #dictionary
x = {"apple", "banana", "cherry"} #set
x = frozenset({"apple", "banana", "cherry"}) #frozenset	
x = True	#bool	
x = b"Hello"	#bytes	
x = bytearray(5)	#bytearray	
x = memoryview(bytes(5))	#memoryview	
x = None
